### PR TITLE
Using --holdver when calling makepkg and archbuild.

### PR DESCRIPTION
**Pull request by yuyichao**
Updating versions should be done in pre_build.

### CODE REVIEW

**Comment by lilydjwg** [comment]
@yuyichao do you still remember why this was added? It causes some other issues at https://github.com/archlinuxcn/repo/issues/1391 and I am thinking about reverting this change.

**Comment by yuyichao** [comment]
80% sure it's to make sure the version does not change between prebuild/version checking and building.

IIRC the version check and the building aren't done back to back (which would reduce the change of an update happening in between) and the version check and compilation of other packages may happen in between.

**Comment by lilydjwg** [comment]
What issue does this prevent? VCS packages do not update to the version reported by nvchecker, but to the version when `vcs_update` is run. The version changes will make the build log report wrong versions but that's a minor issue (and it's fixable). What's more, the building chroot is always updated to latest.

What do you mean by "compilation of other packages". Packages during one run are not expected to check versions of each other. And the latest built dependent packages are always used.

**Comment by yuyichao** [comment]
I checked out an old version of the repo to check what I was using at the time. I'm pretty sure it's still about version conssistency but I now belieeve it's probably the consistency between the multiple prefixes. That is not currently a problem now although I feel like it is still more correct to update the version before the build....

I do kind of remember there was something else in prebuild that either caches or depends on the version but I didn't spot anything obvious at a glance = = ....

**Comment by yan12125** [comment]
I haven't seen a VCS package that uses the version string from nvchecker in `pre_build()`. I believe those are edge cases, if any. Removing `--holdver` should make many other package work with simpler `lilac.*` config files, and packages that really need it can use `makepkg_args`.

**Pull request merged**
