### PR TITLE
Implement rpkgs nvchecker source for CRAN and Bioconductor

### PR DESCRIPTION
**Pull request by pekkarr**
This source fetches and caches the `PACKAGES.gz` file of the repo.

Optimized and expanded from lilydjwg/nvchecker#184

### CODE REVIEW

**Review by lilydjwg — CHANGES_REQUESTED** [review]
Please add a test.

Also, should we deprecate the `cran` source?

**Comment by pekkarr** [comment]
Tests and the better error message are now implemented.

> Also, should we deprecate the `cran` source?

In my opinion, no. The `cran` source is lightweight for checking a few versions, since it fetches the version info only for the requested packages unlike `rpkgs` which fetches the whole version database.

Quoting comment from https://github.com/lilydjwg/nvchecker/pull/184#issuecomment-853557501

> However, I don't quite like to download the whole database just for a few entries. Even crawling the web page is better than that.

In lilac it makes sense to download the whole database, since there are almost 4000 R packages in the Bioarchlinux repo. For other nvchecker users this might not be the case.

And besides, this source is in lilac (unless you want me to make a pr for nvchecker?)

**Comment by lilydjwg** [comment]
Oops, I didn't notice it's the lilac repo here. Let's keep it with lilac for the time being.

**Comment by lilydjwg** [comment]
The tests need an update: https://github.com/archlinuxcn/lilac/actions/runs/8402877668/job/23012743437

**Comment by pekkarr** [comment]
The tests pass on my machine, and also on the [BioArchLinux build](https://build.bioarchlinux.org/api/pkg/lilac/log/1711217148).

In the GitHub actions job, it looks like curl can't find or access the certificate store. I'm not sure how to fix this.

```
tornado.curl_httpclient.CurlError: HTTP 599: error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

**Comment by lilydjwg** [comment]
Oh I see. The same issue I've fixed for nvchecker repo.

**Pull request merged**
