### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by Xuanwo**
fix https://github.com/archlinuxcn/lilac/issues/35 .

### CODE REVIEW

**Comment by lilydjwg** [comment]
Where will `pypi2pkgbuild` and `recv_gpg_keys` be installed? And what about `config.ini.sample`?

**Comment by Xuanwo** [comment]
Maybe we should change the current behavior for `may_download_winterpy_libs` which will lead to `NotADirectoryError: [Errno 20] Not a directory` error while running `lilac`.

`winterpy` should under control of git submodule or via pip instead of downloading directly.

**Comment by lilydjwg** [comment]
I prefer to vendor them.

**Comment by lilydjwg** [comment]
Vendored。

**Comment by Xuanwo** [comment]
How about remove the `sys.path.append` from `lilac`, and use `vendor.myutils` instead ?

**Comment by lilydjwg** [comment]
> How about remove the sys.path.append from lilac, and use vendor.myutils instead ?

It's better but needs a lot of work to update all imports. Also it's better to do as `lilac2.vendor.xxx`.

**Comment by Xuanwo** [comment]
What's the relation between `lilac2`, `lilaclib`, `pylib` and `vendor` ?

Maybe we can move all code into a split package, and keep `lilac` as a simple script to call them?
If you agree, I can submit a draft and finish the refactor for that.

**Comment by lilydjwg** [comment]
lilaclib is the old one, lilac2 is a refactoring one. vendor is utils from winterpy (called pylib previously).

**Comment by yan12125** [comment]
Hi @Xuanwo are you still working on this? If not, may I finish this based on your work?

**Comment by Xuanwo** [comment]
@yan12125 It will be great if you can continue on this!

**Comment by yan12125** [comment]
Thanks!

**Pull request closed without merging**
