### PR TITLE
added `--noprepare` in vcs_update()

### PR DESCRIPTION
**Pull request by petronny**
如题，我觉得是没必要运行prepare()的。。。

### CODE REVIEW

**Comment by lilydjwg** [comment]
原来还有这么个选项。

**Comment by yan12125** [comment]
This change breaks `linux-jwrdegoede` [1]:

> /home/lilydjwg/archgitrepo/archlinuxcn/linux-jwrdegoede/PKGBUILD: 第 36 行：cd: linux-sunxi: 没有那个文件或目录
> ==> 错误： pkgver 不允许为空。

In the corresponding PKGBUILD, prepare() clones the main git repo [2], and thus skipping `prepare()` breaks `vcs_update()`.

For this specific case, I think PKGBUILD should be modified. /cc @farseerfc

[1] https://build.archlinuxcn.org/~yan12125/lilac-log/2019-09-06T01%3A17%3A01
[2] https://github.com/archlinuxcn/repo/blob/39653b606736cef6d16fb338418ffe9ed94d2640/archlinuxcn/linux-jwrdegoede/PKGBUILD#L47

**Comment by lilydjwg** [comment]
@masakichi 的 mecab-ipadic-neologd-git 也有在 prepare 进行 git clone 的问题呢。

**Comment by farseerfc** [comment]
@yan12125 thanks, I am trying to revert to normal git repo in source array

**Pull request merged**
